#!/usr/bin/env node

require('colors');
var nopt = require('nopt');

var yate = require('./yatelib.js');

var parsed = nopt({
    'ast': Boolean,
    'print': Boolean,
    'module': String,
    'mode': String
});

var mode = parsed.mode || '';
var module = parsed.module || 'default';

var template = parsed.argv.remain[0];
var data = parsed.argv.remain[1];
var externals = parsed.argv.remain[2];

if (!template) {
    console.log('Usage: yate [ --module name ] template.yate');
    console.log('       yate [ --mode mode ] template.yate data.json [ external.js ]');
    console.log('       yate --ast template.yate');
    console.log('       yate --print template.yate');
    return 10;
}

if (parsed.ast) {
    var ast = yate.parse(template);
    console.log( yate.walk(ast).toString() );

} else if (parsed.print) {
    var ast = yate.parse(template);
    console.log( ast.yate() );

} else if (data) {
    console.log( yate.run(template, data, externals, mode) );

} else {
    console.log( yate.compile(template, module) );

}

// vim: set filetype=javascript:

