#!/usr/bin/env node

var fs_ = require('fs');

var yate = require('./lib/yate.js');

//  ---------------------------------------------------------------------------------------------------------------  //

var nopt = require('nopt');

var parsed = nopt(
    {
        'ast': Boolean,
        'print': Boolean,
        'mode': String,
        'output': String
    },
    {
        'a': '--ast',
        'p': '--print',
        'm': '--mode',
        'o': '--output'
    }
);

var mode = parsed.mode || '';

var template = parsed.argv.remain[0];
var data = parsed.argv.remain[1];
var externals = parsed.argv.remain[2];

if (!template) {
    console.log('Usage: yate --output template.js template.yate');
    console.log('       yate [ --mode mode ] template.yate data.json [ external.js ]');
    console.log('       yate --ast template.yate');
    console.log('       yate --print template.yate');
    return 10;
}

//  ---------------------------------------------------------------------------------------------------------------  //

if (parsed.ast) {
    var ast = yate.parse(template);
    console.log( yate.walk(ast).toString() );

} else if (parsed.print) {
    var ast = yate.parse(template);
    console.log( ast.yate() );

} else if (data) {
    console.log( yate.run(template, { filename: data }, externals, mode) );

} else {
    var js = yate.compile(template);
    if (parsed.output) {
        fs_.writeFileSync(parsed.output, js, 'utf-8');
    } else {
        console.log(js);
    }

}

//  ---------------------------------------------------------------------------------------------------------------  //

// vim: set filetype=javascript:

