#!/usr/bin/env node

require('../colors.js');

var fs = require('fs');
var yate = require('../yatelib.js');
var tests = require('./tests.js');

for (var i = 0, l = tests.length; i < l; i++) {
    var test = tests[i];

    var result = yate.run( test.yate, test.data );

    if (result == test.result) {
        console.log('%s\t%s\t%s', test.yate.gray, 'ok'.green, test.description.gray );
    } else {
        console.log('%s\t%s\t%s', test.yate.white, 'fail'.red, test.description.white );
    }
}

